# Generated by Django 3.2.23 on 2024-05-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240510_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Nairobi', max_length=255),
        ),
    ]
